---
train:

    params:
        batch_size: 256
        epoch: 80
        lr: 0.0005
        decay: 0.5
        decay_step: 60
        warmup: 5

    save:
        metapath: "/root/autodl-tmp/RESULT/mpii"
        folder: rt
        model_name: trans6
        step: 10

    data:
        image: "/root/autodl-tmp/RTGENE_3D/RTGene"
        label: "/root/autodl-tmp/RTGENE_3D/Label/train" 
        header: True
        name: rt
        isFolder: True

        
    pretrain:
        enable: False
        path: ""
        device: 0

    device: 0

    reader: reader

